apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::383495572941:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::383495572941:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-HUPEGGF0UJWZ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-15T04:52:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2193"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: aeef139d-70a4-4a32-a34a-b4ab570e0e92
